### ISSUE TITLE
GitLab integration not working

### ISSUE THREAD

**Issue by askannon** [RocketChat/Rocket.Chat.Ops#44]
I am running Gitsy as part of the rocketchat/hubot-rocketchat docker image. The bot seems to be ok at first and "hubot intro gitsy" outputs the correct manual. But running any GitLab integration command like e.g. "hubot projects" is causing the folllowing trace:

```
rocketchat_hubot        | [Mon Aug 01 2016 18:33:51 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'body' of null
rocketchat_hubot        |   at /home/hubot/node_modules/hubot-gitsy/src/gitlab/lib/ApiBaseHTTP.js:82:56
rocketchat_hubot        |   at _Class.wrap_response (/home/hubot/node_modules/hubot-gitsy/node_modules/slumber/lib/API.js:197:18)
rocketchat_hubot        |   at _Class.<anonymous> (/home/hubot/node_modules/hubot-gitsy/node_modules/slumber/lib/API.js:4:59)
rocketchat_hubot        |   at Request._callback (/home/hubot/node_modules/hubot-gitsy/node_modules/slumber/lib/API.js:215:26)
rocketchat_hubot        |   at self.callback (/home/hubot/node_modules/hubot-gitsy/node_modules/slumber/node_modules/request/request.js:187:22)
rocketchat_hubot        |   at Request.emit (events.js:129:20)
rocketchat_hubot        |   at Request.onRequestError (/home/hubot/node_modules/hubot-gitsy/node_modules/slumber/node_modules/request/request.js:813:8)
rocketchat_hubot        |   at ClientRequest.emit (events.js:107:17)
rocketchat_hubot        |   at _http_outgoing.js:415:12
rocketchat_hubot        |   at process._tickCallback (node.js:355:11)
```

Any ideas what might be causing this?

Thanks

**Comment by evagonz** [comment]
I have this problem as well.

**Comment by pasmon** [comment]
We have the same issue.

OS: CentOS 7.2
Docker: 1.12.3
Docker Compose: 1.8.1
Rocket.Chat: 0.45.0
hubot-rocketchat: 1.0.6
hubot-gitsy: 0.8.3

**Comment by bbrauns** [comment]
Same issue

**Comment by M-throwaway** [comment]
Can confirm. The same issue.

**Comment by reetp** [comment]
See here for the latest:

https://github.com/RocketChat/hubot-gitsy
